### PR TITLE
Feature weather app

### PR DESCRIPTION
**Pull request by abeidahmed**
## Features

- Search by city name
- Display temperature, min temperature, max temperature
- Display the city's current weather status. Eg: clear, cloudy, rainy, etc
- Change the background of the app dynamically according to the city's current weather status
- Toggle temperature unit between Celsius and Fahrenheit (the state is persistent)

### CODE REVIEW

**Comment by descholar-ceo** [comment]
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @abeidahmed  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implement all of the minimal requirements of this project, keep it up, and your project is really almost done.
:+1: Almost everything is working as expected
#### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] In the getting started section of your readme file, there is this step: `Run git pull origin feature-weather-app` , why is it necessary to pull that branch? I think it is not needed at all. Explanation is like this: The readme file will remain as the homepage of your project even after merging this branch to the base branch, that means all of the codes on this branch will be present on the base branch and when we clone the base branch is checked out by default, since everything will be on the base branch then there is no need to look for other branches. This step should be removed from the getting started steps.

- [x] Your repository is professional when the information presented on the readme file is accurate: After following all the getting started steps, I ran `npm run dev` but the app is not accessible on `localhost:3000`, => that may make your repo unprofessional at all, could you fix that issue?

- [x] There is something I noticed which might be wrong: When I toggle the unit, the appearance of the app is being changed as if the new equivalence of the value is a new result, that shouldn't be like that. Actually when we toggle the unit, it is the same value/result but displayed in different units, that means the appearance should remain the same. Learn the following screenshots to know more about that issue

| Tokyo with degree Celsius |Tokyo with Fahrenheit |
| --- | --- |
|Screenshot from 2021-03-12 08-54-34 | Screenshot from 2021-03-12 08-55-49 |

:point_right: Could you see the difference :question: :question: :question: 

# [Optional changes] :yellow_circle: 
- [ ] The weather app should have a ‘loading’ component that displays from the time the form is submitted until the information comes back from the API ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/loading_component_requirement.png) from Odin)
- [ ] The weather app should fetch the current geolocation of the user when the app is first accessed and fetches the weather from that location
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by abeidahmed** [comment]
> # Status: Changes Required  
> ## Hello @abeidahmed   
>  This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
>  I liked that you have tried to implement all of the minimal requirements of this project, keep it up, and your project is really almost done.
>  Almost everything is working as expected
> 
> ####  However we need to make few changes to mark this project approved. See the requested change below   
> ### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding
> # [Required Changes] 
> * [ ]  In the getting started section of your readme file, there is this step: `Run git pull origin feature-weather-app` , why is it necessary to pull that branch? I think it is not needed at all. Explanation is like this: The readme file will remain as the homepage of your project even after merging this branch to the base branch, that means all of the codes on this branch will be present on the base branch and when we clone the base branch is checked out by default, since everything will be on the base branch then there is no need to look for other branches. This step should be removed from the getting started steps.
> * [ ]  Your repository is professional when the information presented on the readme file is accurate: After following all the getting started steps, I ran `npm run dev` but the app is not accessible on `localhost:3000`, => that may make your repo unprofessional at all, could you fix that issue?
> * [ ]  There is something I noticed which might be wrong: When I toggle the unit, the appearance of the app is being changed as if the new equivalence of the value is a new result, that shouldn't be like that. Actually when we toggle the unit, it is the same value/result but displayed in different units, that means the appearance should remain the same. Learn the following screenshots to know more about that issue
> 
> Tokyo with degree Celsius	Tokyo with Fahrenheit
> Screenshot from 2021-03-12 08-54-34	Screenshot from 2021-03-12 08-55-49
>  Could you see the difference   
> 
> # [Optional changes] 
> * [ ]  The weather app should have a ‘loading’ component that displays from the time the form is submitted until the information comes back from the API ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/loading_component_requirement.png) from Odin)
> * [ ]  The weather app should fetch the current geolocation of the user when the app is first accessed and fetches the weather from that location
> 
> _If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._
> 
> [GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)
> 
> _Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

Thank you for reviewing my project. Regarding the unit toggle feature, I just make a request to the server and ask them for the Fahrenheit unit. That is it. I debugged the API response, and it is the API that is returning different results and probably not the fault of the code that I have written itself.
Thanks again. I will solve the first 2 issues and request for a review again.

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

**Pull request merged**
